In [145]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler



borders = pd.read_csv('GEODATASOURCE-COUNTRY-BORDERS.csv')
data15 = pd.read_csv('2015.csv')
data16 = pd.read_csv('2016.csv')
data17 = pd.read_csv('2017.csv')
three_data_year = pd.read_csv('Three-Year-Data.csv')

In [6]:
# three_data_year.groupBy('Country')

In [7]:
three_year_data = pd.read_csv('Three-Year-Data.csv')
data15_region_subset = data15.loc[:,['Region','Country']]

In [8]:
three_data_year = three_data_year.merge(data15_region_subset, how='inner',left_on='Country Name',right_on='Country')
three_data_year = three_data_year.drop(['Country'], axis=1)
# three_data_year = three_data_year[three_data_year['Country Name'],three_data_year[]]
three_data_year_2015 = three_data_year.loc[:,['Country Name','Region','Country Border Name','Happiness Score 2015']]

In [9]:
three_data_year_2015

,Country Name,Region,Country Border Name,Happiness Score 2015
0,United Arab Emirates,Middle East and Northern Africa,Oman,6.853
1,United Arab Emirates,Middle East and Northern Africa,Saudi Arabia,6.411
2,Afghanistan,Southern Asia,China,5.140
3,Afghanistan,Southern Asia,Iran,4.686
4,Afghanistan,Southern Asia,Pakistan,5.194
5,Afghanistan,Southern Asia,Tajikistan,4.786
6,Afghanistan,Southern Asia,Turkmenistan,5.548
7,Afghanistan,Southern Asia,Uzbekistan,6.003
8,Albania,Central and Eastern Europe,Greece,4.857
9,Albania,Central and Eastern Europe,Montenegro,5.192
10,Albania,Central and Eastern Europe,Macedonia,5.007
11,Albania,Central and Eastern Europe,Serbia,5.123
12,Armenia,Central and Eastern Europe,Azerbaijan,5.212
13,Armenia,Central and Eastern Europe,Georgia,4.297
14,Armenia,Central and Eastern Europe,Iran,4.686
15,Armenia,Central and Eastern Europe,Turkey,5.332
16,Angola,Sub-Saharan Africa,Togo,2.839
17,Angola,Sub-Saharan Africa,Togo,2.839
18,Angola,Sub-Saharan Africa,Namibia,NaN
19,Angola,Sub-Saharan Africa,Zambia,5.129
20,Argentina,Latin America and Caribbean,Brazil,6.983
21,Argentina,Latin America and Caribbean,Chile,6.670
22,Argentina,Latin America and Caribbean,Paraguay,5.878
23,Argentina,Latin America and Caribbean,Uruguay,6.485
24,Austria,Western Europe,Czech Republic,6.505
25,Austria,Western Europe,Germany,6.750
26,Austria,Western Europe,Hungary,4.800
27,Austria,Western Europe,Italy,5.948
28,Austria,Western Europe,Slovakia,5.995
29,Austria,Western Europe,Slovenia,5.848
...,...,...,...,...
504,Uzbekistan,Central and Eastern Europe,Kazakhstan,5.855
505,Uzbekistan,Central and Eastern Europe,Kyrgyzstan,5.286
506,Uzbekistan,Central and Eastern Europe,Tajikistan,4.786
507,Uzbekistan,Central and Eastern Europe,Turkmenistan,5.548
508,Venezuela,Latin America and Caribbean,Brazil,6.983
509,Venezuela,Latin America and Caribbean,Colombia,6.477
510,Venezuela,Latin America and Caribbean,Ghana,4.633
511,Vietnam,Southeastern Asia,Cambodia,3.819
512,Vietnam,Southeastern Asia,China,5.140
513,Vietnam,Southeastern Asia,Laos,4.876
514,Yemen,Middle East and Northern Africa,Oman,6.853
515,Yemen,Middle East and Northern Africa,Saudi Arabia,6.411
516,South Africa,Sub-Saharan Africa,Botswana,4.332
517,South Africa,Sub-Saharan Africa,Lesotho,4.898
518,South Africa,Sub-Saharan Africa,Mozambique,4.971
519,South Africa,Sub-Saharan Africa,Namibia,NaN
520,South Africa,Sub-Saharan Africa,Swaziland,4.867
521,South Africa,Sub-Saharan Africa,Zimbabwe,4.610
522,Zambia,Sub-Saharan Africa,Angola,4.033
523,Zambia,Sub-Saharan Africa,Botswana,4.332
524,Zambia,Sub-Saharan Africa,Togo,2.839
525,Zambia,Sub-Saharan Africa,Malawi,4.292
526,Zambia,Sub-Saharan Africa,Mozambique,4.971
527,Zambia,Sub-Saharan Africa,Namibia,NaN
528,Zambia,Sub-Saharan Africa,Tanzania,3.781
529,Zambia,Sub-Saharan Africa,Zimbabwe,4.610
530,Zimbabwe,Sub-Saharan Africa,Botswana,4.332
531,Zimbabwe,Sub-Saharan Africa,Mozambique,4.971
532,Zimbabwe,Sub-Saharan Africa,South Africa,4.642
533,Zimbabwe,Sub-Saharan Africa,Zambia,5.129

In [10]:
groupby_region = three_data_year_2015.groupby('Country Name')['Region'].count().reset_index()

In [11]:
groupby_region = groupby_region[groupby_region['Region'] >= 3]

In [12]:
groupby_region

    Country Name  Region
0    Afghanistan       6
1        Albania       4
2        Algeria       6
3         Angola       4
4      Argentina       4
..           ...     ...
127   Uzbekistan       5
128    Venezuela       3
129      Vietnam       3
131       Zambia       8
132     Zimbabwe       4

[91 rows x 2 columns]

In [165]:
group_region = three_data_year_2015.groupby(['Region','Country Name']).count().reset_index()
group_region_number3 = group_region[group_region['Country Border Name'] >= 2]
group_region_number3.drop('Happiness Score 2015',axis=1)
doto = three_data_year_2015.merge(group_region_number3,how = 'inner',left_on = 'Country Name',right_on = 'Country Name').drop(['Country Border Name_y'],axis=1)
doto = doto.rename(columns={'Happiness Score 2015_y':'NoOfNeighbours'})
doto

,Country Name,Region_x,Country Border Name_x,Happiness Score 2015_x,Region_y,NoOfNeighbours
0,United Arab Emirates,Middle East and Northern Africa,Oman,6.853,Middle East and Northern Africa,2
1,United Arab Emirates,Middle East and Northern Africa,Saudi Arabia,6.411,Middle East and Northern Africa,2
2,Afghanistan,Southern Asia,China,5.140,Southern Asia,6
3,Afghanistan,Southern Asia,Iran,4.686,Southern Asia,6
4,Afghanistan,Southern Asia,Pakistan,5.194,Southern Asia,6
5,Afghanistan,Southern Asia,Tajikistan,4.786,Southern Asia,6
6,Afghanistan,Southern Asia,Turkmenistan,5.548,Southern Asia,6
7,Afghanistan,Southern Asia,Uzbekistan,6.003,Southern Asia,6
8,Albania,Central and Eastern Europe,Greece,4.857,Central and Eastern Europe,4
9,Albania,Central and Eastern Europe,Montenegro,5.192,Central and Eastern Europe,4
10,Albania,Central and Eastern Europe,Macedonia,5.007,Central and Eastern Europe,4
11,Albania,Central and Eastern Europe,Serbia,5.123,Central and Eastern Europe,4
12,Armenia,Central and Eastern Europe,Azerbaijan,5.212,Central and Eastern Europe,4
13,Armenia,Central and Eastern Europe,Georgia,4.297,Central and Eastern Europe,4
14,Armenia,Central and Eastern Europe,Iran,4.686,Central and Eastern Europe,4
15,Armenia,Central and Eastern Europe,Turkey,5.332,Central and Eastern Europe,4
16,Angola,Sub-Saharan Africa,Togo,2.839,Sub-Saharan Africa,3
17,Angola,Sub-Saharan Africa,Togo,2.839,Sub-Saharan Africa,3
18,Angola,Sub-Saharan Africa,Namibia,NaN,Sub-Saharan Africa,3
19,Angola,Sub-Saharan Africa,Zambia,5.129,Sub-Saharan Africa,3
20,Argentina,Latin America and Caribbean,Brazil,6.983,Latin America and Caribbean,4
21,Argentina,Latin America and Caribbean,Chile,6.670,Latin America and Caribbean,4
22,Argentina,Latin America and Caribbean,Paraguay,5.878,Latin America and Caribbean,4
23,Argentina,Latin America and Caribbean,Uruguay,6.485,Latin America and Caribbean,4
24,Austria,Western Europe,Czech Republic,6.505,Western Europe,7
25,Austria,Western Europe,Germany,6.750,Western Europe,7
26,Austria,Western Europe,Hungary,4.800,Western Europe,7
27,Austria,Western Europe,Italy,5.948,Western Europe,7
28,Austria,Western Europe,Slovakia,5.995,Western Europe,7
29,Austria,Western Europe,Slovenia,5.848,Western Europe,7
...,...,...,...,...,...,...
491,Uzbekistan,Central and Eastern Europe,Kazakhstan,5.855,Central and Eastern Europe,5
492,Uzbekistan,Central and Eastern Europe,Kyrgyzstan,5.286,Central and Eastern Europe,5
493,Uzbekistan,Central and Eastern Europe,Tajikistan,4.786,Central and Eastern Europe,5
494,Uzbekistan,Central and Eastern Europe,Turkmenistan,5.548,Central and Eastern Europe,5
495,Venezuela,Latin America and Caribbean,Brazil,6.983,Latin America and Caribbean,3
496,Venezuela,Latin America and Caribbean,Colombia,6.477,Latin America and Caribbean,3
497,Venezuela,Latin America and Caribbean,Ghana,4.633,Latin America and Caribbean,3
498,Vietnam,Southeastern Asia,Cambodia,3.819,Southeastern Asia,3
499,Vietnam,Southeastern Asia,China,5.140,Southeastern Asia,3
500,Vietnam,Southeastern Asia,Laos,4.876,Southeastern Asia,3
501,Yemen,Middle East and Northern Africa,Oman,6.853,Middle East and Northern Africa,2
502,Yemen,Middle East and Northern Africa,Saudi Arabia,6.411,Middle East and Northern Africa,2
503,South Africa,Sub-Saharan Africa,Botswana,4.332,Sub-Saharan Africa,5
504,South Africa,Sub-Saharan Africa,Lesotho,4.898,Sub-Saharan Africa,5
505,South Africa,Sub-Saharan Africa,Mozambique,4.971,Sub-Saharan Africa,5
506,South Africa,Sub-Saharan Africa,Namibia,NaN,Sub-Saharan Africa,5
507,South Africa,Sub-Saharan Africa,Swaziland,4.867,Sub-Saharan Africa,5
508,South Africa,Sub-Saharan Africa,Zimbabwe,4.610,Sub-Saharan Africa,5
509,Zambia,Sub-Saharan Africa,Angola,4.033,Sub-Saharan Africa,7
510,Zambia,Sub-Saharan Africa,Botswana,4.332,Sub-Saharan Africa,7
511,Zambia,Sub-Saharan Africa,Togo,2.839,Sub-Saharan Africa,7
512,Zambia,Sub-Saharan Africa,Malawi,4.292,Sub-Saharan Africa,7
513,Zambia,Sub-Saharan Africa,Mozambique,4.971,Sub-Saharan Africa,7
514,Zambia,Sub-Saharan Africa,Namibia,NaN,Sub-Saharan Africa,7
515,Zambia,Sub-Saharan Africa,Tanzania,3.781,Sub-Saharan Africa,7
516,Zambia,Sub-Saharan Africa,Zimbabwe,4.610,Sub-Saharan Africa,7
517,Zimbabwe,Sub-Saharan Africa,Botswana,4.332,Sub-Saharan Africa,4
518,Zimbabwe,Sub-Saharan Africa,Mozambique,4.971,Sub-Saharan Africa,4
519,Zimbabwe,Sub-Saharan Africa,South Africa,4.642,Sub-Saharan Africa,4
520,Zimbabwe,Sub-Saharan Africa,Zambia,5.129,Sub-Saharan Africa,4

In [173]:



data = doto 
arr = pd.DataFrame()
a = list(data.groupby('Country Name')['Happiness Score 2015_x'])
for i in range(len(a)):
    val = a[i][1].tolist()
    arr.loc[i,0] = a[i][0]
    arr.loc[i,1] = val[0]
    arr.loc[i,2] = val[1]

arr.rename(columns = {0:'name',1:'a',2:'b'},inplace = True)    
arr2 = arr.merge(data15[['Country','Happiness Score']],how = 'inner',left_on = 'name',right_on = 'Country').drop(['name'],axis=1)
arr2
X = arr2[['a','b']]
y = arr2[['Happiness Score']]
X_train, X_valid, y_train, y_valid = train_test_split(X, y)
model = make_pipeline(
    SimpleImputer(strategy='mean'), # impute missing values
    MinMaxScaler(),                 # scale each feature to 0-1
    LinearRegression(fit_intercept=True)
)
model.fit(X_train, y_train)
result = (model.predict(X))

arr2['res'] = result
print(model.score(X_train, y_train))
print(model.score(X_valid, y_valid))

print(arr2.loc[arr2['Country']=='Ukraine'])

0.5288671974604353
0.6767200372375954
         a    b  Country  Happiness Score       res
110  5.813  4.8  Ukraine            4.681  5.198829

                      Country  Happiness Score
0                 Switzerland            7.587
1                     Iceland            7.561
2                     Denmark            7.527
3                      Norway            7.522
4                      Canada            7.427
5                     Finland            7.406
6                 Netherlands            7.378
7                      Sweden            7.364
8                 New Zealand            7.286
9                   Australia            7.284
10                     Israel            7.278
11                 Costa Rica            7.226
12                    Austria            7.200
13                     Mexico            7.187
14              United States            7.119
15                     Brazil            6.983
16                 Luxembourg            6.946
17                    Ireland            6.940
18                    Belgium            6.937
19       United Arab Emirates            6.901
20             United Kingdom            6.867
21                       Oman            6.853
22                  Venezuela            6.810
23                  Singapore            6.798
24                     Panama            6.786
25                    Germany            6.750
26                      Chile            6.670
27                      Qatar            6.611
28                     France            6.575
29                  Argentina            6.574
..                        ...              ...
128                   Myanmar            4.307
129                   Georgia            4.297
130                    Malawi            4.292
131                 Sri Lanka            4.271
132                  Cameroon            4.252
133                  Bulgaria            4.218
134                     Egypt            4.194
135                     Yemen            4.077
136                    Angola            4.033
137                      Mali            3.995
138       Congo (Brazzaville)            3.989
139                   Comoros            3.956
140                    Uganda            3.931
141                   Senegal            3.904
142                     Gabon            3.896
143                     Niger            3.845
144                  Cambodia            3.819
145                  Tanzania            3.781
146                Madagascar            3.681
147  Central African Republic            3.678
148                      Chad            3.667
149                    Guinea            3.656
150               Ivory Coast            3.655
151              Burkina Faso            3.587
152               Afghanistan            3.575
153                    Rwanda            3.465
154                     Benin            3.340
155                     Syria            3.006
156                   Burundi            2.905
157                      Togo            2.839

[158 rows x 2 columns]